### PR TITLE
Added Script to Upload PowerBI Application into a Workspace

### PR DESCRIPTION
**Pull request by sgsshankar**
Script will upload Power BI applications from a local folder into the specified Workspace. The workspace will be created if it does not exist.

### CODE REVIEW

**Comment by sgsshankar** [comment]
@guyinacube Can you please review the PR and do a merge if possible :)

Thanks

**Comment by guyinacube** [comment]
Can you update the script to use the Power BI PowerShell CMDLETs instead of the direct REST API calls? we are working on moving examples to that. It removes a lot of overhead.

**Comment by sgsshankar** [comment]
Sure i can. I will make the changes and provide in the PR.

**Comment by sgsshankar** [comment]
Powershell Commandlets updated. Closing this and opening a new Pull request

**Pull request closed without merging**
